Repository Like-Lion-NSU/Elementary_School, pull requests merged in 2024-07, with the labels that each got.

#29 feat : refreshToken을 이용한 accessToken 재발급 및 로그아웃
  BE/school/src/main/java/thisisus/school/auth/controller/AuthController.java
  BE/school/src/main/java/thisisus/school/auth/exception/AlreadyLoggedOutException.java
  BE/school/src/main/java/thisisus/school/auth/exception/MemberRefreshTokenMismatchException.java
  BE/school/src/main/java/thisisus/school/auth/infrastructure/AuthTokenGenerator.java
  BE/school/src/main/java/thisisus/school/auth/infrastructure/JwtTokenProvider.java
  BE/school/src/main/java/thisisus/school/auth/service/AuthService.java
  BE/school/src/main/java/thisisus/school/auth/service/AuthServiceImpl.java
  BE/school/src/main/java/thisisus/school/auth/service/RefreshTokenValidator.java
  BE/school/src/main/java/thisisus/school/common/exception/ExceptionCode.java
Labels: Type: Feature/Function, Status: Reviewing

#28 feat : 게시글 좋아요 관련 엔터티 설계 및 구현
  BE/school/src/main/java/thisisus/school/post/domain/PostLike.java
  BE/school/src/test/java/thisisus/school/post/service/PostServiceImplTest.java
Labels: Type: Feature/Function, Status: In Progress

#32 feat : 레디스 의존성 주입 및 기본 설정
  BE/school/build.gradle
  BE/school/src/main/java/thisisus/school/SchoolApplication.java
  BE/school/src/main/java/thisisus/school/redis/common/CommonRedisRepository.java
  BE/school/src/main/java/thisisus/school/redis/config/RedisCacheConfig.java
  BE/school/src/main/java/thisisus/school/redis/config/RedisConfig.java
Labels: Type: Feature/Function

#34 refactor : Redis를 이용해서 RefreshToken 관리 및 OIDC Key를 캐싱하여 관리
  BE/school/src/main/java/thisisus/school/auth/config/AuthenticationExtractor.java
  BE/school/src/main/java/thisisus/school/auth/controller/AuthController.java
  BE/school/src/main/java/thisisus/school/auth/controller/AuthenticatedMemberResolver.java
  BE/school/src/main/java/thisisus/school/auth/controller/interceptor/AuthenticationInterceptor.java
  BE/school/src/main/java/thisisus/school/auth/dto/request/SignUpRequest.java
  BE/school/src/main/java/thisisus/school/auth/exception/TokenTypeMismatchException.java
  BE/school/src/main/java/thisisus/school/auth/infrastructure/AuthTokenGenerator.java
  BE/school/src/main/java/thisisus/school/auth/infrastructure/JwtTokenProvider.java
  BE/school/src/main/java/thisisus/school/auth/infrastructure/kakao/RequestKakaoOauthClient.java
  BE/school/src/main/java/thisisus/school/auth/service/AuthService.java
  BE/school/src/main/java/thisisus/school/auth/service/AuthServiceImpl.java
  BE/school/src/main/java/thisisus/school/auth/service/RefreshTokenValidator.java
  BE/school/src/main/java/thisisus/school/common/exception/ExceptionCode.java
  BE/school/src/main/java/thisisus/school/member/controller/MemberController.java
  BE/school/src/main/java/thisisus/school/member/domain/Member.java
  BE/school/src/main/java/thisisus/school/member/dto/UpdateMemberRequest.java
  BE/school/src/main/java/thisisus/school/redis/Auth/domain/RefreshToken.java
  BE/school/src/main/java/thisisus/school/redis/Auth/exception/ExpiredTokenException.java
  BE/school/src/main/java/thisisus/school/redis/Auth/repository/RefreshTokenRedisRepository.java
  BE/school/src/main/java/thisisus/school/redis/Auth/service/RefreshTokenRedisService.java
  BE/school/src/main/java/thisisus/school/redis/Auth/service/RefreshTokenRedisServiceImpl.java
Labels: Type: Feature/Function, Status: Reviewing

#31 feat : 게시글 좋아요, 좋아요 해제 구현 및 테스트코드 작성
  BE/school/src/main/java/thisisus/school/common/exception/ExceptionCode.java
  BE/school/src/main/java/thisisus/school/post/controller/PostLikeController.java
  BE/school/src/main/java/thisisus/school/post/domain/Post.java
  BE/school/src/main/java/thisisus/school/post/exception/AlreadyExistPostLikeException.java
  BE/school/src/main/java/thisisus/school/post/exception/NotExistPostLikeException.java
  BE/school/src/main/java/thisisus/school/post/repository/PostLikeRepository.java
  BE/school/src/main/java/thisisus/school/post/repository/PostRepository.java
  BE/school/src/main/java/thisisus/school/post/service/PostLikeService.java
  BE/school/src/main/java/thisisus/school/post/service/PostLikeServiceImpl.java
  BE/school/src/test/java/thisisus/school/post/service/PostLikeServiceImplTest.java
  BE/school/src/test/java/thisisus/school/post/service/PostLikeSynchronousTest.java
Labels: Type: Feature/Function, Status: Reviewing
